### ISSUE TITLE
[Bug]: iOS Unity Plist config is never set in the AppboyAppDelegate

### ISSUE THREAD

**Issue by DigiDen** [braze-inc/braze-unity-sdk#100]
### Braze Unity SDK Version

4.1.0

### Steps To Reproduce

Follow unity ios integration guide, set automatic push notification integration for ios to true.
Build the game for xcode.
Start the game.

### Expected Behavior

The plist values should be propagated to the AppboyAppDelegate

### Actual Incorrect Behavior

Observe the Appboy delegate being called in "didFinishLaunchingWithOptions"
A braze instance will be created and the property self.brazeUnityPlist will be accessed, which was not set before so the dictionary is null resulting in all checks for AutomaticPushIntegrationKey to fail and push will not register the token with braze backend.

**Comment by spielepalast** [comment]
Any updates on this issue?

**Comment by lowip** [comment]
Hi @DigiDen and @spielepalast, thanks for reporting this issue.

We are currently trying to reproduce the issue and are tracking it internally. We'll update here as soon as we have an update.

**Comment by lowip** [comment]
Hi @DigiDen,

We have released 4.1.1 which resolves the issue, a line was missing in our sample integration. You can see the change [here](https://github.com/braze-inc/braze-unity-sdk/compare/4.1.0...4.1.1#diff-f6410c89993c1290570aaefe971115d020cb56801b83b3cf1cbb1cbd032ec1a8R33-R34).

Feel free to re-open the thread if you're still experiencing the issue.
